keys:
  - &admin_doridian_keepassxc age1m27t2k0tyh23rt6925m8dacvkmz559deht2yelun9s7h3scsfa4q6hdjcl
  - &server_bengalfox age1hdgjgrzk9lq88f3vwxtf4p9fnmjkuzdf4ykcg8p7kgf3t8hgxqvqenv5fl
  - &server_islandfox age142dhgtgtgm6kv252pd8ypt3xnvvzl2qavycvme9yqzyesktcwuyq8w3u22
  - &server_icefox age1cs2u7xvd88ukwh9hptpzdxq728a692jxxajtqtqkrqxyv0ld2a6s2mgxvm
# First hit rule counts
creation_rules:
  - path_regex: '^secrets/shared\.'
    key_groups:
      - age:
        - *admin_doridian_keepassxc
        - *server_bengalfox
        - *server_islandfox
        - *server_icefox
  - path_regex: '^secrets/bengalfox\.'
    key_groups:
      - age:
        - *admin_doridian_keepassxc
        - *server_bengalfox
  - path_regex: '^secrets/icefox\.'
    key_groups:
      - age:
        - *admin_doridian_keepassxc
        - *server_icefox
  - path_regex: '^secrets/islandfox\.'
    key_groups:
      - age:
        - *admin_doridian_keepassxc
        - *server_islandfox
  - path_regex: '^secrets/zfs-zhdd\.'
    key_groups:
      - age:
        - *admin_doridian_keepassxc
        - *server_bengalfox
  - path_regex: '^secrets/zfs-ztank\.'
    key_groups:
      - age:
        - *admin_doridian_keepassxc
        - *server_icefox
