keys:
  - &admin_doridian_keepassxc age1m27t2k0tyh23rt6925m8dacvkmz559deht2yelun9s7h3scsfa4q6hdjcl
  - &device_bengalfox age1hdgjgrzk9lq88f3vwxtf4p9fnmjkuzdf4ykcg8p7kgf3t8hgxqvqenv5fl
  - &device_carvera-controller age1txw8phmwtv0ce3kya5e0spmwvkt05h2v9cqcrtngyz6653xr6pkqxf7w5s
  - &device_islandfox age142dhgtgtgm6kv252pd8ypt3xnvvzl2qavycvme9yqzyesktcwuyq8w3u22
  - &device_icefox age1cs2u7xvd88ukwh9hptpzdxq728a692jxxajtqtqkrqxyv0ld2a6s2mgxvm
# First hit rule counts
creation_rules:
  - path_regex: '^secrets/shared\.'
    key_groups:
      - age:
        - *admin_doridian_keepassxc
        - *device_bengalfox
        - *device_islandfox
        - *device_icefox
        - *device_carvera-controller
  - path_regex: '^secrets/bengalfox\.'
    key_groups:
      - age:
        - *admin_doridian_keepassxc
        - *device_bengalfox
  - path_regex: '^secrets/carvera-controller\.'
    key_groups:
      - age:
        - *admin_doridian_keepassxc
        - *device_carvera-controller
  - path_regex: '^secrets/icefox\.'
    key_groups:
      - age:
        - *admin_doridian_keepassxc
        - *device_icefox
  - path_regex: '^secrets/islandfox\.'
    key_groups:
      - age:
        - *admin_doridian_keepassxc
        - *device_islandfox
  - path_regex: '^secrets/zfs-zhdd\.'
    key_groups:
      - age:
        - *admin_doridian_keepassxc
        - *device_bengalfox
  - path_regex: '^secrets/zfs-ztank\.'
    key_groups:
      - age:
        - *admin_doridian_keepassxc
        - *device_icefox
