defaults:
  backends:
    default:
      host: 169.254.169.254
    http:
      port: 80
    https:
      port: 443
    quic:
      port: 443
hosts:
  api.spaceage.mp:
    template: spaceage-api-default
  archlinux.foxden.network:
    template: mirror-default
  auth.foxden.network:
    template: auth-default
  cachyos.foxden.network:
    template: mirror-default
  darksignsonline.com:
    template: darksignsonline-default
  darksignsonline.foxden.network:
    template: darksignsonline-default
  doridian.de:
    template: doridian-website-default
  doridian.net:
    template: doridian-website-default
  e621.foxden.network:
    template: e621dumper-default
  f0x.es:
    template: foxcaves-default
  foxcav.es:
    template: foxcaves-default
  foxcaves.foxden.network:
    template: foxcaves-default
  furaffinity.foxden.network:
    template: fadumper-default
  git.foxden.network:
    template: git-default
  grafana.foxden.network:
    template: grafana-default
  homeassistant.foxden.network:
    template: homeassistant-default
  jellyfin.foxden.network:
    template: jellyfin-default
  kiwix.foxden.network:
    template: kiwix-default
  mirror.foxden.network:
    template: mirror-default
  nas.foxden.network:
    template: nas-default
  radius.auth.foxden.network:
    template: radius-default
  restic.foxden.network:
    template: restic-default
  spaceage-api.foxden.network:
    template: spaceage-api-default
  spaceage-tts.foxden.network:
    template: spaceage-tts-default
  spaceage-website.foxden.network:
    template: spaceage-website-default
  spaceage.mp:
    template: spaceage-website-default
  syncthing.foxden.network:
    template: syncthing-default
  tts.spaceage.mp:
    template: spaceage-tts-default
  webdav.syncthing.foxden.network:
    template: syncthing-default
  website.foxden.network:
    template: doridian-website-default
  www.darksignsonline.com:
    template: darksignsonline-default
  www.doridian.de:
    template: doridian-website-default
  www.doridian.net:
    template: doridian-website-default
  www.f0x.es:
    template: foxcaves-default
  www.foxcav.es:
    template: foxcaves-default
  www.spaceage.mp:
    template: spaceage-website-default
listeners:
  http: :80
  https: :443
  prometheus: :9001
  quic: :443
templates:
  auth-default:
    default:
      host: 10.1.14.1
      proxyProtocol: true
    http:
      port: 80
    https:
      port: 443
    quic:
      port: 443
  darksignsonline-default:
    default:
      host: 10.3.10.15
      proxyProtocol: true
    http:
      port: 80
    https:
      port: 443
    quic:
      port: 443
  doridian-website-default:
    default:
      host: 10.2.11.15
      proxyProtocol: true
    http:
      port: 80
    https:
      port: 443
    quic:
      port: 443
  e621dumper-default:
    default:
      host: 10.2.11.18
      proxyProtocol: true
    http:
      port: 80
    https:
      port: 443
    quic:
      port: 443
  fadumper-default:
    default:
      host: 10.2.11.19
      proxyProtocol: true
    http:
      port: 80
    https:
      port: 443
    quic:
      port: 443
  foxcaves-default:
    default:
      host: 10.3.10.1
      proxyProtocol: true
    http:
      port: 81
    https:
      port: 444
    quic:
      port: 443
  git-default:
    default:
      host: 10.2.11.13
      proxyProtocol: true
    http:
      port: 80
    https:
      port: 443
    quic:
      port: 443
  grafana-default:
    default:
      host: 10.2.11.5
      proxyProtocol: true
    http:
      port: 80
    https:
      port: 443
    quic:
      port: 443
  homeassistant-default:
    default:
      host: 10.2.12.2
      proxyProtocol: false
    http:
      port: 80
    https:
      port: 443
    quic:
      port: 443
  jellyfin-default:
    default:
      host: 10.2.11.3
      proxyProtocol: true
    http:
      port: 80
    https:
      port: 443
    quic:
      port: 443
  kiwix-default:
    default:
      host: 10.2.11.6
      proxyProtocol: true
    http:
      port: 80
    https:
      port: 443
    quic:
      port: 443
  mirror-default:
    default:
      host: 10.2.11.17
      proxyProtocol: true
    http:
      port: 81
    https:
      port: 444
    quic:
      port: 443
  nas-default:
    default:
      host: 10.2.11.1
      proxyProtocol: true
    http:
      port: 80
    https:
      port: 443
    quic:
      port: 443
  radius-default:
    default:
      host: 10.1.14.2
      proxyProtocol: true
    http:
      port: 80
    https:
      port: 443
    quic:
      port: 443
  restic-default:
    default:
      host: 10.2.11.12
      proxyProtocol: true
    http:
      port: 80
    https:
      port: 443
    quic:
      port: 443
  spaceage-api-default:
    default:
      host: 10.3.10.5
      proxyProtocol: true
    http:
      port: 80
    https:
      port: 443
    quic:
      port: 443
  spaceage-tts-default:
    default:
      host: 10.3.10.6
      proxyProtocol: true
    http:
      port: 80
    https:
      port: 443
    quic:
      port: 443
  spaceage-website-default:
    default:
      host: 10.3.10.9
      proxyProtocol: true
    http:
      port: 80
    https:
      port: 443
    quic:
      port: 443
  syncthing-default:
    default:
      host: 10.2.11.2
      proxyProtocol: true
    http:
      port: 80
    https:
      port: 443
    quic:
      port: 443
