name: Cachetest

on:
  push:
    branches:
      - main

jobs:
  cachetest:
    runs-on: ubuntu-latest
    steps:
    - run: |
        set -x
        ifconfig || ip addr
        curl -m 5 -v "${ACTIONS_CACHE_URL}/ping"
