name: Cachetest

on:
  push:
    branches:
      - main

jobs:
  cachetest:
    runs-on: ubuntu-latest
    steps:
    - run: |
        set -x
        sudo apt-get install -y iproute2
        ip addr
        ip link
        ip route
        curl -m 5 -v https://git.foxden.network
        curl -m 5 -v "${ACTIONS_CACHE_URL}/ping"
