on:
  push:
    branches:
      - main

concurrency:
  cancel-in-progress: true
  group: deploy-${{ github.ref }}

jobs:
  deploy:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        target: [bengalfox.foxden.network, islandfox.foxden.network, icefox.foxden.network]
    steps:
      - uses: https://data.forgejo.org/actions/checkout@v6
      - name: Deploy to target
        run: |
          echo 'Deploying to target: ${{ matrix.target }}'
          touch /tmp/nixpush_key
          chmod 600 /tmp/nixpush_key
          echo '${{ secrets.NIXPUSH_KEY }}' > /tmp/nixpush_key
          ssh -i /tmp/nixpush_key 'nixpush@${{ matrix.target }}'
