on: [push]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Tests :3
        run: |
          docker ps || true
          docker pull docker.io/ubuntu:24.04
          docker run --rm -v /:/data --entrypoint=/bin/ls docker.io/ubuntu:24.04 -- -la /data
