on:
  pull_request:
  push:
    branches:
      - main

concurrency:
  cancel-in-progress: true
  group: lint-${{ github.ref }}

jobs:
  lint:
    runs-on: ubuntu-24.04
    steps:
      - uses: https://data.forgejo.org/actions/checkout@v6
      - uses: https://github.com/astral-sh/setup-uv@v7
      - uses: https://github.com/cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-25.11
          github_access_token: ${{ secrets.EXT_GITHUB_TOKEN }}
      - name: Lint nix
        run: |
          cd ./nix
          nix run 'nixpkgs#nixfmt-tree' -- --ci
      - name: Lint mikrotik
        run: |
          cd ./mikrotik
          uv run ruff check

      - uses: https://github.com/terraform-linters/setup-tflint@v6
        name: Setup TFLint
        with:
          tflint_version: v0.59.1

      - name: Init TFLint
        run: tflint --init

      - name: Run TFLint
        run: tflint -c "${PWD}/terraform/.tflint.hcl" --recursive -f compact
