on: [push]
jobs:
  print-content:
    runs-on: default
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: list directory contents
        run: docker build -t core .
