on: [push]
jobs:
  lint:
    runs-on: default
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: Say hi
        run: echo Hello
      - name: Build dev container
        run: |
          mkdir -p hostexecutor
          podman build -t core .
