on: [push]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: Lint nix
        run: |
          cd ./nix
          echo $DOCKER_HOST
          treefmt --ci
      - name: Lint mikrotik
        run: |
          cd ./mikrotik
          uv run ruff check
