on: [push]
jobs:
  lint:
    runs-on: default
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: Build dev container
        run: |
          ls /proc
          podman image rm core || true
          podman build -t core .
