on: [push]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: github.com/astral-sh/setup-uv@v7
      - uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - name: Lint nix
        run: |
          cd ./nix
          treefmt --ci
      - name: Lint mikrotik
        run: |
          cd ./mikrotik
          uv run ruff check
