[[inputs.snmp]]
  agents = [ "ats-rack.foxden.network" ]
  version = 1
  community = "${SNMP_COMMUNITY}"
  interval = "60s"
  timeout = "10s"
  retries = 3

  [[inputs.snmp.field]]
    name = "hostname"
    oid = "SNMPv2-MIB::sysName.0"
    is_tag = true

  [[inputs.snmp.field]]
    name = "uptime"
    oid = "DISMAN-EXPRESSION-MIB::sysUpTimeInstance"

  [[inputs.snmp.field]]
    name = "model"
    oid = "CPS-MIB::atsIdentModelName.0"

  [[inputs.snmp.field]]
      name = "name"
      oid = "CPS-MIB::atsIdentName.0"

  [[inputs.snmp.field]]
      name = "atsStatusSelectedSource"
      oid = "CPS-MIB::atsStatusSelectedSource.0"
      conversion = "float(0)"

  [[inputs.snmp.field]]
      name = "atsStatusInputVoltage"
      oid = "CPS-MIB::atsStatusInputVoltage.1"
      conversion = "float(1)"

  [[inputs.snmp.field]]
      name = "atsStatusInputVoltageB"
      oid = "CPS-MIB::atsStatusInputVoltage.2"
      conversion = "float(1)"

  [[inputs.snmp.field]]
      name = "atsLoadStatusPhasePower"
      oid = "CPS-MIB::atsLoadStatusPhasePower.1"
      conversion = "float(0)"

  [[inputs.snmp.table]]
    oid = "CPS-MIB::atsStatusInputTable"
    [[inputs.snmp.table.field]]
        oid = "CPS-MIB::atsStatusInputVoltage"
        conversion = "float(1)"
    [[inputs.snmp.table.field]]
        oid = "CPS-MIB::atsStatusInputFrequency"
        conversion = "float(1)"
