- job_name: node
  static_configs:
    - targets: ['bengalfox.foxden.network:9100', 'islandfox.foxden.network:9100', 'ntpi.foxden.network:9100', 'homeassistant.foxden.network:9100', 'icefox.doridian.net:9100']

- job_name: telegraf
  static_configs:
    - targets: ['telegraf.foxden.network:9273']

- job_name: homeassistant
  metrics_path: /api/prometheus
  authorization:
    credentials: '__HOMEASSISTANT_API_TOKEN__'
  scheme: https
  static_configs:
    - targets: ['homeassistant.foxden.network:443']

- job_name: prometheus
  static_configs:
    - targets: ['127.0.0.1:9090']

- job_name: deluge
  static_configs:
    - targets: ['dldr.foxden.network:9100']

- job_name: mktxp
  static_configs:
    - targets: ['mktxp.foxden.network:49090']

- job_name: foxingress
  static_configs:
    - targets: ['router.foxden.network:5303', 'router-backup.foxden.network:5303', 'icefox.foxden.network:5303']
