apiVersion: 1
groups:
    - orgId: 1
      name: Fridge temperature alert
      folder: General Alerting
      interval: 1m
      rules:
        - uid: gjlqfAk4z
          title: Fridge temperature alert
          condition: B
          data:
            - refId: A
              relativeTimeRange:
                from: 3600
                to: 0
              datasourceUid: "000000002"
              model:
                editorMode: builder
                expr: homeassistant_sensor_temperature_celsius{entity="sensor.fridge_temperature"}
                intervalMs: 1000
                legendFormat: __auto
                maxDataPoints: 43200
                range: true
                refId: A
            - refId: B
              datasourceUid: "-100"
              model:
                conditions:
                    - evaluator:
                        params:
                            - 10
                        type: gt
                      operator:
                        type: and
                      query:
                        params:
                            - A
                      reducer:
                        params: []
                        type: avg
                      type: query
                datasource:
                    type: __expr__
                    uid: "-100"
                intervalMs: 1000
                maxDataPoints: 43200
                refId: B
                type: classic_conditions
          dashboardUid: y157P7IZz
          panelId: 6
          noDataState: NoData
          execErrState: Alerting
          for: 5m
          annotations:
            __dashboardUid__: y157P7IZz
            __panelId__: "6"
          labels: {}
          isPaused: false
