apiVersion: 1
groups:
    - orgId: 1
      name: NTP sanity alert
      folder: General Alerting
      interval: 1m
      rules:
        - uid: jMAkxBCnkz
          title: NTP sanity alert
          condition: B
          data:
            - refId: A
              queryType: randomWalk
              relativeTimeRange:
                from: 300
                to: 0
              datasourceUid: "prometheus"
              model:
                exemplar: true
                expr: node_ntp_sanity
                interval: ""
                intervalMs: 1000
                legendFormat: '{{instance}}'
                maxDataPoints: 43200
                queryType: randomWalk
                refId: A
            - refId: B
              datasourceUid: "-100"
              model:
                conditions:
                    - evaluator:
                        params:
                            - 0.9
                        type: lt
                      operator:
                        type: and
                      query:
                        params:
                            - A
                      reducer:
                        type: avg
                intervalMs: 1000
                maxDataPoints: 43200
                refId: B
                type: classic_conditions
          dashboardUid: mqTCPng4k
          panelId: 10
          noDataState: NoData
          execErrState: Alerting
          for: 5m
          annotations:
            __alertId__: "7"
            __dashboardUid__: mqTCPng4k
            __panelId__: "10"
          labels:
            alertname: NTP sanity alert
            rule_uid: jMAkxBCnkz
          isPaused: false
