#!/usr/bin/env bash
set -euo pipefail

rsync -a --delete /run/appliance/app/ /run/appliance/data/app/
chmod -R 700 /run/appliance/data/app

cd /run/appliance/data
exec /run/appliance/data/app/CarveraController
